### ISSUE TITLE
checkAvailability serialization exception if service not available

### ISSUE THREAD

**Issue by ALobastov** [ServicePattern/MobileAPI_Android#39]
Steps:
1. In the messaging entry configuration page configure the Hours of Operation so the service is not available at the time of test
2. In the mobile app, call checkAvailability() method

Result: serialization exception:

D/NetworkService: ---------- IN ---------->
    200
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Headers: Accept, Origin, Content-type, Authorization
    Access-Control-Allow-Methods: GET, POST
    Connection: keep-alive
    Content-Length: 23
    Content-Type: application/json;charset=utf-8
    Date: Mon, 28 Jun 2021 19:07:09 GMT
    Server: nginx/1.19.2
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    X-Android-Received-Millis: 1624907227849
    X-Android-Response-Source: NETWORK 200
    X-Android-Selected-Protocol: http/1.1
    X-Android-Sent-Millis: 1624907227786
    
    {"chat":"notAvailable"}
    
    ------------------------->
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.brightpattern.chatdemo, PID: 6246
    kotlinx.serialization.SerializationException: com.brightpattern.bpcontactcenter.model.ContactCenterServiceChatAvailability does not contain element with name 'notAvailable'
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.getElementIndexOrThrow(TreeJsonDecoder.kt:292)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(StreamingJsonDecoder.kt:222)
        at com.brightpattern.bpcontactcenter.model.ContactCenterServiceChatAvailability$$serializer.deserialize(Unknown Source:11)
        at com.brightpattern.bpcontactcenter.model.ContactCenterServiceChatAvailability$$serializer.deserialize(ContactCenterServiceAvailability.kt:9)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at com.brightpattern.bpcontactcenter.model.ContactCenterServiceAvailability$$serializer.deserialize(Unknown Source:83)
        at com.brightpattern.bpcontactcenter.model.ContactCenterServiceAvailability$$serializer.deserialize(ContactCenterServiceAvailability.kt:20)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
        at com.brightpattern.bpcontactcenter.ContactCenterCommunicator$checkAvailability$1.onResponse(ContactCenterCommunicator.kt:142)
        at com.brightpattern.bpcontactcenter.ContactCenterCommunicator$checkAvailability$1.onResponse(ContactCenterCommunicator.kt:38)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process: Sending signal. PID: 6246 SIG: 9
Disconnected from the target VM, address: 'localhost:64285', transport: 'socket'

**Comment by bramley-stride** [comment]
We are seeing this issue in production, causing our app to crash. According to https://github.com/ServicePattern/MobileAPI_Android/releases there is no new release available. Can you please publish a new version with this fix?
